version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install --global --unsafe-perm sharp-cli expo-cli
      - npm install --force
  pre_build:
    commands:
      # - export EXPO_CLI_PASSWORD=$(aws ssm get-parameter --name "expo-cli-password" --region "us-east-1" --query 'Parameter.Value' --with-decryption --output text)
      - npx expo login --non-interactive -u ${EXPO_USERNAME} -p ${EXPO_CLI_PASSWORD}
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the actual code
      - expo publish
      # - expo build:web
      - expo build:android -t apk --no-wait
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Android build status can be checked at https://expo.dev/
# artifacts:
#   files:
#     - './**/*'
#   base-directory: web-build
#   name: SocialJusticeWarriors

cache:
  paths:
    - './node_modules/**/*'